[package]
name = "paperclip-core"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]
edition = "2018"
description = "Core types and traits for paperclip OpenAPI tooling library"
documentation = "https://paperclip.waffles.space/paperclip_core"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/wafflespeanut/paperclip"
repository = "https://github.com/wafflespeanut/paperclip"

[dependencies]
actix-web = { version = "3.0.0-alpha.1", optional = true }
actix-http = { version = "2.0.0-alpha.2", optional = true }
chrono = { version = "0", optional = true }
failure = "0.1"
heck = { version = "0.3", optional = true }
lazy_static = "1.3"
log = { version = "0.4", optional = true }
mime = { git = "https://github.com/hyperium/mime", features = ["serde1"] }
paperclip-macros = { path = "../macros", version = "0.2.0" }
parking_lot = "0.10"
rust_decimal = { version = "1", optional = true }
regex = "1.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_yaml = "0.8"
uuid = { version = "0", optional = true }

[features]
actix = ["v2", "actix-http", "actix-web"]
codegen = ["heck", "log"]
datetime = ["chrono"]
decimal = ["rust_decimal"]
default = ["v2", "codegen"]
nightly = ["paperclip-macros/nightly"]
uid = ["uuid"]
v2 = ["paperclip-macros/v2"]
